FROM node:14-alpine3.13
RUN apk --no-cache add git
RUN git config --global user.email "eric_soucy_1@yahoo.ca"
RUN git config --global user.name "ericsoucy"
WORKDIR /monsters-rolodex
COPY ./monsters-rolodex/package*.json ./
RUN npm install
EXPOSE 3000
#COPY ./monsters-rolodex/public ./public
#COPY ./monsters-rolodex/src ./src

